// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Database, SupabaseRPCFunctions } from './types';

// We're using direct database operations now, no need for custom RPC types

const SUPABASE_URL = "https://zmzquibcjxfsjzplffyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptenF1aWJjanhmc2p6cGxmZnl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMzAwNDQsImV4cCI6MjA2MjgwNjA0NH0.JyfXnXnqdmrM5HI_BNPEF0VNBdHbmNYpzAaKh6wQVec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);